on: pull_request_target

name: "Dependabot: auto-merge patch versions"

jobs:
  approve-dependabot-pr:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and merge Dependabot PRs for patch versions
        if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        uses: actions/github-script@v5
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            await github.rest.pulls.createReview({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'APPROVE',
              body: '@dependabot merge',
            })
