on: pull_request_target

name: "Dependabot: auto-merge patch versions"

jobs:
  approve-dependabot-pr:
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@8348ea7f5d949b08c7f125a44b569c9626b05db3 # v1.7.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve and merge Dependabot PRs for patch versions
        if: ${{github.event.workflow_run.conclusion == 'success' && steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch'}}
        uses: ridedott/merge-me-action@338053c6f9b9311a6be80208f6f0723981e40627 # v2.10.122
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
